### ISSUE TITLE
Update to use Node 16

### ISSUE THREAD

**Issue by dataviruset** [shrink/actions-docker-extract#11]
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: shrink/actions-docker-extract@v1

**Comment by dataviruset** [comment]
Thanks for the quick fix and for a useful action overall :)

**Comment by shrink** [comment]
@dataviruset no problem! I'm just preparing to release the update as `v2` -- I'll ping you here once it's available to upgrade to in your actions :)

**Comment by shrink** [comment]
@dataviruset node16 is released now as v2.0.0 (also tagged as `v2`) so you can update whenever is convenient.

```yaml
- uses: shrink/actions-docker-extract@v2
```

Let me know if you run into any issues!

**Comment by dataviruset** [comment]
> @dataviruset node16 is released now as v2.0.0 (also tagged as `v2` and `v2.0`) so you can update whenever is convenient.
> 
> ```yaml
> - uses: shrink/actions-docker-extract@v2
> ```
> 
> Let me know if you run into any issues!

Seems to be working all right for me. Thanks again!
